Extension { #name : #KeyboardKey }

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F1 [
	
	^ self value: 65470
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F10 [
	
	^ self value: 65479
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F11 [
	
	^ self value: 65480
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F12 [
	
	^ self value: 65481
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F2 [
	
	^ self value: 65471
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F3 [
	
	^ self value: 65472
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F4 [
	
	^ self value: 65473
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F5 [
	
	^ self value: 65474
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F6 [
	
	^ self value: 65475
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F7 [
	
	^ self value: 65476
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F8 [
	
	^ self value: 65477
]

{ #category : #'*Spec-Gtk-Keybindings' }
KeyboardKey class >> F9 [
	
	^ self value: 65478
]


